### ISSUE TITLE
Not (yet?) open source

### ISSUE THREAD

**Issue by jpetso** [witheve/eve-native#54]
[In your announcement](https://groups.google.com/forum/#!msg/eve-talk/YFguOGkNrBo/EozaCfheAQAJ), you mention that you've open sourced the Eve runtime, with a link to this repository. However, the README mentions _(c) 2017 Kodowa Inc, All Rights Reserved_, the package.json says _"license": "UNLICENSED"_, the source files don't have a license headers and there's no LICENSE.txt or similar file.

So it's not really open source at this point. By publishing it on GitHub, you would have agreed to the minimum GitHub requirements (i.e. let other people fork your code) but for all practical purposes, it's still proprietary code. I imagine this is not your intention and these things are just the way they are because it just happened half a day ago or so, and you've been busy with other important stuff.

I thought it might be a good idea to point this out while everything's still fresh, and to make sure the situation is clarified one way or another. Thanks for your work and all the best!

**Comment by ibdknox** [comment]
You are totally right. I've added a LICENSE and updated the readme to state that it's all meant to be under the Apache 2 license.

**Comment by jpetso** [comment]
Thanks! I think this is sufficient to close this issue as clarified and "now indeed open source".
